trigger:
  branches:
    include:
      - master  # or your branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
# 1) Install Node
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node'

# 2) Install backend dependencies
- script: |
    cd backend
    npm install
  displayName: 'Install backend dependencies'

# 3) Zip the backend code dynamically for deployment
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'backend'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/backend.zip'
    replaceExistingArchive: true
  displayName: 'Archive backend folder'

# 4) (Optional) Publish artifact in pipeline UI
- publish: '$(Build.ArtifactStagingDirectory)/backend.zip'
  artifact: drop

# 5) Deploy to Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure-SC'  # Your service connection name in DevOps
    appName: 'ecomwebapp'           # Your Azure Web App name
    package: '$(Build.ArtifactStagingDirectory)/backend.zip'
    deploymentMethod: 'zipDeploy'
  displayName: 'Deploy backend to Azure Web App'
