trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node'

# Backend dependencies
- script: |
    cd backend
    npm install
  displayName: 'Install backend dependencies'

# Frontend build
- script: |
    cd frontend
    npm install
    npm run build
  displayName: 'Build React frontend'

# Copy frontend build to backend folder
- script: |
    cp -r frontend/build backend/build
  displayName: 'Copy frontend build to backend'

# Archive backend + frontend
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'backend'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true
  displayName: 'Zip backend + frontend'

# Publish artifact (optional)
- publish: '$(Build.ArtifactStagingDirectory)/app.zip'
  artifact: drop

# Deploy to Azure
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure-SC'
    appName: 'ecomwebapp'
    package: '$(Build.ArtifactStagingDirectory)/app.zip'
    deploymentMethod: 'zipDeploy'
  displayName: 'Deploy backend + frontend to Azure Web App'
